### PR TITLE
Crowdin v2 fixes

### PR DESCRIPTION
**Pull request by tetatetit**
Fixed some problems/bugs found during testing on all platforms as well as reported by @vslavik by email

### CODE REVIEW

**Comment by vslavik** [comment]
>  Fix getting proj and file IDs from filename

Sorry for having introduced that; it is fixed as a side-effect of c53547e6.

**Comment by vslavik** [comment]
> Fix upload to Crowdin on Save when opened locally  … d7f17d7

See #638 — I'm having doubts about whether Poedit *should* sync on save.

**Comment by vslavik** [comment]
> Fix crash on saving PO downloaded in browser 

Finally this part is outdated based on https://github.com/vslavik/poedit/pull/633#issuecomment-652560673, as we can just remove that code, no?

**Comment by tetatetit** [comment]
> > Fix upload to Crowdin on Save when opened locally  … [d7f17d7](https://github.com/vslavik/poedit/commit/d7f17d73cffed9a916794c394b0e403bb54eb4bc)
> 
> See #638 — I'm having doubts about whether Poedit _should_ sync on save.

It worked same way in v2.3 Poedit and IMO it's properly/useful (why not? what disadvantages it might cause for users?)

**Comment by tetatetit** [comment]
Done using of `X-Crowdin-Project-ID` and `X-Crowdin-File-ID` in 43870fc19a20aebe171e90d4e5c0dcf8aa8c94b8

**Comment by tetatetit** [comment]
> > Fix crash on saving PO downloaded in browser
> 
> Finally this part is outdated based on [#633 (comment)](https://github.com/vslavik/poedit/pull/633#issuecomment-652560673), as we can just remove that code, no?

Yep, pls feel free to remove that outdated commit from this branch/PR or let me know so I would remote it on my own

**Comment by vslavik** [comment]
> It worked same way in v2.3 

I don't think that's true - [this was the only AttachCloudSync use](https://github.com/vslavik/poedit/blob/7a0e93fff167ae5aa786d7b74f7e16b78464c88c/src/edframe.cpp#L1102)

> IMO it's properly/useful (why not? what disadvantages it might cause for users?)

- the linked bug you discovered
- failure to sync presents as failure to save
- confusing UI with two buttons doing the same (see the bug)
- inconsistent behavior between opening-from-crowdin and opening-from-recent-files

**Comment by vslavik** [comment]
> Use `X-Crowdin-Project-ID` and `X-Crowdin-File-ID` 

Non-conflicting commit as 79e1f920 — thanks!

**Comment by tetatetit** [comment]
>
> It worked same way in v2.3
>

Yep I checked, it really does not upload if to `Save` files opened from
local cache (from recent files) bu does if opened via `Open from Crowdin`
or when downloaded in browser via Crowdin UI. Sorry for confusion, but
isn't it inconsistent behaviour for `Save` that in one case it just saves
locally while in another still uploads to Crowdin?

 the linked bug you discovered


Which one bug?

failure to sync presents as failure to save



   1. Why is the same failure ok if `Open from Crowdin` and then `Save` but
   not ok if `Save` opened from local cache or downloaded in browser via
   Crowdin UI?
   2. Why not just to first Save locally and then to upload?


 confusing UI with two buttons doing the same (see the bug)



   1. Then why `Save` of the file opened via `Open from Crowdin` still
   uploads to Crowdin while `Save` of file opened from local cache or
   downloaded in browser via Crowdin UI does not? Isn't it confusing even
   more? At least for me it is. So IMO then it should not upload on `Save` in
   none case to avoid confusions and keep same logic/behaviour for `Save` in
   all cases - i.e. just to save file locally on the disk without any upload.
   2. Which one bug?


inconsistent behavior between opening-from-crowdin and
> opening-from-recent-files
>

Inconsistent when `Save` of opened from local cache (from recent files)
uploads to Crowdin or when not? And the same for `Save` downloaded in
browser from Crowdin UI. Because  I am confused here since in 2.3 `Save` of
opened via `Open from Crowdin` saves locally and uploads to Crowdin while
`Save` of downloaded in browser from Crowdin UI does not but just saves
locally? Isn't exactly such behaviour/logic inconsistent, while IMO it
would be consistent if `Save` either would not upload in all cases or
opposite would upload in all cases?

**Comment by vslavik** [comment]
> Which one bug?

#638 repeatedly referenced above.

>  Isn't it confusing even more?

Yes, as I said, the UI is confusing and I need to figure out what to do. Which is why I won't be introducing any new inconsistent behaviors until I figure it out.

The current state is no worse than 2.3. Changes here can wait until after 2.4.

**Comment by tetatetit** [comment]
I got you now completely. Then since it affects user experience with
Crowdin - why not just to never upload on `Save` regardless it's opened via
`Open from Crowdin`, downloaded in browser via Crowdin UI or from local
cache (resen files)? It would be a quick simple fix while would make
behaviour of `Save` related to Crowdin consistent? While later you/we would
come with some better solution if found? I see that what you propose to
keep the same as in 2.3 is not worse than 2.3. :), but it's definitely not
good as well so making `Save` just save locally (and never upload) would
make it quite consistent IMO and would solve this problem quite quickly and
easily for a while for 2.4 I think. Unless I miss something here.

**Comment by vslavik** [comment]
> but it's definitely not
good as well so making `Save` just save locally (and never upload) would
make it quite consistent IMO and would solve this problem quite quickly and
easily for a while for 2.4 I think. 

Yep. There are actually *four* cases and I failed to consider them all:

1. Open from Crowdin, edit, sync back.
2. Open from recent files as a shortcut for 1., with intent to sync to Crowdin.
3. Open a manually downloaded file, with intent to sync to Crowdin. 
4. Open a file that *happens* to have Crowdin metadata, with no desire to sync.

Case 4 is e.g. when opening Poedit's own PO files — they are downloaded from Crowdin, they report as being sync-capable. But I absolutely *do not want* my changes when playing with the files to sync. They *happen* to be sync friendly, but I didn't download them from Crowdin manually for that purpose. 

So Save behavior in these cases is:

1. Save could be said to be expected to sync, hence the motivation for having it that way (it does now)
2. It's OK to sync on save.
3. It's OK to sync on save.
4. Save **MUST NOT** sync.

And then there are 4 more cases, same as above with "...but while being offline" appended.

So I don't see any other safe and consistent way to do it in 2.4 other than not syncing on Save at all, as you suggest. What I am worried about is that it is non-obvious for previous users, or even for new ones, that Save is local-only. There should be some indicator of # of not-yet-uploaded changes, or a prompt telling to sync on closing (or saving) the file, or *something*.

**Comment by tetatetit** [comment]
> So I don't see any other safe and consistent way to do it in 2.4 other than not syncing on Save at all, as you suggest. What I am worried about is that it is non-obvious for previous users, or even for new ones, that Save is local-only. There should be some indicator of # of not-yet-uploaded changes, or a prompt telling to sync on closing (or saving) the file, or something.

You definitely better then me know expectations of Poedit customers, but just sharing my own expirience with Poedit about what I  tried to guess intuitively when used Poedit and tried to figure out `Save` behaviour/logic initially

So it's just IMO the best quickest fix for 2.4. would be either
- **Never** upload on `Save`, i.e. in **none** of cases 1, 2, 3/4 while only `Sync` should be used to upload in **all** 1, 2, 3, 4 cases. I.e. `Save` behaviour would be same and consistent i all cases. I.e. just **never** upload.
- Upload on `Save` in 1, 2, but **not 3/4**, while only `Sync` should be used in case of 3/4 to upload. Which should look pretty logical and intuitive as well since when customer expect file to be uploaded back when opened via `Open from Crowdin` - IMO it's logically and intuitively to expect it to be uploaded back in case it opened from local cache (`Recent`) (since customer aware that it has been opened via `Open from Crowdin` before as well).

**Comment by vslavik** [comment]
> You definitely better then me know expectations of Poedit customers

Expectations are best learned and clarified through conversations like this, which I deeply appreciate...

> Upload on Save in 1, 2, but not 3/4, while only Sync should be used in case of 3/4 to upload.

I think you're right! That indeed seems to be where we should draw the line. I'll make a separate PR for this (together with addressing #638 as this is all related) and ask you to look it over if you don't mind.

**Comment by vslavik** [comment]
I think this one is outdated now, right?

**Comment by tetatetit** [comment]
> I think this one is outdated now, right?

Yep, if you mean this branch/PR

**Pull request closed without merging**
