### PR TITLE
Update configure check for pugixml

### PR DESCRIPTION
**Pull request by c72578**
- Add check for headers and lib if
  pugixml.pc is not available

### CODE REVIEW

**Comment by vslavik** [comment]
Sorry, why wouldn't `pugixml.pc` be available?

**Comment by vslavik** [comment]
I see.

But honestly, I'd rather not do this here — it nontrivially complicates the code (i.e. kind of eliminates the whole point of `pkg-config`). Rationale: For users compiling from sources for their own needs, it shouldn't matter than a bundled copy is used. Presumably this only matters to distros and there a better fix is to simply enable the respective option when building the pugixml package, no?

**Comment by c72578** [comment]
Makes sense, not to "workaround" here at Poedit. Sooner or later a new release of pugixml will improve the situation concerning pugixml.pc

**Comment by c72578** [comment]
Just for the records:
pugixml v1.10 has been released [1] and pugixml.pc is installed now by default.

[1] https://github.com/zeux/pugixml/releases

**Pull request closed without merging**
