### PR TITLE
configure.ac: check for system json.hpp if available, and use it

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
(Issue: #372)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: f9f0cd8366c2277ab0437c820c108f9dacfbf53d
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
I assume you tested that this does the right thing (i.e. still compiles if you delete the embedded file) on Debian?

**Comment by LocutusOfBorg** [comment]
yes, it works when I remove the system library (it uses the embedded one) and it works when the system one is installed.
(also the -Dflag is injected correctly)

**Comment by vslavik** [comment]
Thanks!

**Pull request merged**
