### PR TITLE
Add Danish and Italian translations to poedit.desktop

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 1130b50101d735bf7dacd39c7f4fae100d13a2e6
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
Please follow git [best practices](http://chris.beams.io/posts/git-commit/) and use concise *descriptive* subjects — "sort keys" isn't one (as opposed to e.g. "Sort poedit.desktop entries alphabetically"). Please also don't reference, and especially not in the subject line, issues created for the sole purpose of being referenced in an immediately following commit. There's no reason to tag *additions* that don't *fix* anything that way.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 5f5b5aca430a47d1a6271946cbf8f330df5da4ce
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by LocutusOfBorg** [comment]
I hope it is better now :)

**Comment by vslavik** [comment]
Thanks!

**Pull request merged**
