### PR TITLE
Use static IDs for controls needed by NVDA

### PR DESCRIPTION
**Pull request by vslavik**
This reorganizes Poedit's code to be able to a) assign static IDs safely and b) add more quickly if the need arrises.

See the relevant NVDA plugin's code here: https://github.com/nvaccess/nvda/blob/master/source/appModules/poedit.py

@LeonarddeR I'd appreciate your review if you could spare the time. Most of the changes are internal to Poedit and of little interest, the interesting bit is the `static_id.h` file:

1. Is it understandable?
2. Does it cover NVDA's needs?
3. Can it be improved and/or is there more that you guys need?

I *think* it covers it (`PRO_IDENTIFIER` and `MAIN_SPLITTER_IDENTIFIER` seem to be needed just for the clever/hacky workaround for lack of static IDs), but I'm far from being 100% sure.

### CODE REVIEW

**Comment by LeonarddeR** [comment]
@vslavik I'm really grateful for your kind work, I'm pretty sure this will cover everything we need.
Would it be possible to provide a build of this code others can test too? Preferably I'd like to prototype a poedit.py with the hardcoded control ids to test with so we're absolutely sure that this settles everything we need.

**Comment by vslavik** [comment]
> Would it be possible to provide a build of this code others can test too?

@LeonarddeR Of course!

https://download.poedit.net/tmp/Poedit-3.5nvda-setup.exe

**Comment by LeonarddeR** [comment]
I filed https://github.com/nvaccess/nvda/pull/16889 and tested the build, it seems to work great up until now.

**Comment by vslavik** [comment]
> I filed https://github.com/nvaccess/nvda/pull/16889 and tested the build, it seems to work great up until now.

OK, thanks for testing, I plan to merge it in time for 3.5 (Real Soon Now™).

**Comment by LeonarddeR** [comment]
Thanks @vslavik.
Is there a due date for the release of poedit 3.5?

**Comment by vslavik** [comment]
@LeonarddeR Well, I wanted it to be out for a while now, so... 🤷‍♂️ This month for sure.

**Pull request merged**
