### PR TITLE
Consistent usage of ellipsis and curly quote

### PR DESCRIPTION
**Pull request by fbonzon**
See #338.

### CODE REVIEW

**Comment by vslavik** [comment]
Thanks!

Can you please clean up the PR, though? 

1. Don't have messy reversion commits; you can use `git rebase -i` and `git push -f` to clean the history and squash 290749c and affe38c.

2. Both commits contains numerous changes unrelated to the subject: a) whitespaces removals and b) license comment blocks changes (incl. the entirety of changes to `src/pluralforms/COPYING`).

**Comment by fbonzon** [comment]
Done.

**Comment by vslavik** [comment]
Thanks again for this cleanup work. I added typographically correct strings to [the Crowdin project](https://crowdin.com/project/poedit) now and will merge this PR as soon as most translations are updated.

I also added correction to use proper “quotes” for quoting filenames to this PR.

**Comment by fbonzon** [comment]
I have uploaded the translations on Crowdin for language French.

Also added on Crowdin new translation suggestions in French for source English strings that were not modified in this PR:
- Where existing French translation uses using tripe dot `...` instead of single character `…` (where English was already correctly using single character `…` before this PR).
- Where existing French translation uses straight quote instead of curly quote.

Can you check and approve them ?

French typographic rules also require a thin space (U+202F NARROW NO-BREAK SPACE) before `;` `:` `?` `!`; I fixed this.

**Comment by vslavik** [comment]
> Can you check and approve them ? 

No. The point of proof-reading/approving is that *a translator competent in the language* does that. Use voting to indicate poor translations.

**Pull request merged**
