### PR TITLE
Corrected spelling error in Danish translation

### PR DESCRIPTION
**Pull request by jhertel**
Corrected "Åben" to "Åbn". It's a common grammatical/spelling error in Danish.

### CODE REVIEW

**Comment by vslavik** [comment]
Please submit any translation improvements through http://crowdin.com/project/poedit/ (see also `locales/README`).

Thanks!

**Comment by jhertel** [comment]
I tried for a very long time to find where that specific translation was, including on http://crowdin.com/project/poedit/ (which has a terrible or even missing search system), but failed to find it. Finally I found it here. 

Please tell me the exact URL for that specific translation on http://crowdin.com/project/poedit/ if you still believe it's there.

**Comment by c72578** [comment]
https://crowdin.com/translate/poedit/56/en-da?filter=basic&value=0
However, it is correct there in Crowdin:
Åbn Poedit efter installation

**Comment by jhertel** [comment]
Thanks for the link which illustrates the problem. 

I noticed the problem when I was installing the _latest version_ of Poedit (2.4.2) a few days ago. It said "Åben Poedit efter installation" during the installation, i.e. the wrong string, which was what prompted me to search for that string. Since it has been correctly translated in Crowdin for 6 years I didn't find it there in my search for "Åben".

So the correct Crowdin version at https://crowdin.com/translate/poedit/56/en-da?filter=basic&value=0 is not actually used, as @c72578 (Wolfgang Stöggl) also commented in Crowdin 3 days ago.

So my suggested edit is still relevant until the system is patched so it actually uses the Crowdin translation.

**Comment by jhertel** [comment]
@vslavik This is still an issue, as I wrote in a [previous comment](https://github.com/vslavik/poedit/pull/674#issuecomment-759850568) in January.

I just installed Poedit 2.4.3, and the issue is still there. It's a code issue. So please reopen this, apply the temporary fix I gave, or fix the issue in the code so it actually uses the translation on Crowdin.

**Pull request closed without merging**
