### PR TITLE
Merging new contents from vslavik/poedit

### PR DESCRIPTION
**Pull request by babycaseny**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 74a6495c86ec0b738d729c65f0be56284dfe148d
  * Your subject line is longer than 50 characters

Please see https://github.com/agis-/git-style-guide (you can use `git push -f` to update this PR)

---
This message was auto-generated by https://gitcop.com

**Comment by babycaseny** [comment]
Merged.

**Comment by vslavik** [comment]
Sorry, but no, there’s no way I’m going to merge this horrible mess. Even without considering the subject matter, this is unacceptable on git hygiene grounds: there’s not even a meaningful description of the PR, it’s a big mess of haphazard commits that lack description, are not described in English (?!) or have description *completely unrelated to the content*, touch the same file repeatedly, contain entirely spurious merges and even commit and update *generated log files* specific to your machine.

Please do read https://github.com/agis-/git-style-guide to learn how to use git in a more organized fashion.

And then there’s the subject matter. Put bluntly, I’m not going to add a translation for a made-up language, with a made-up (read: invalid) ISO 639 code that will be — let’s be honest here — immediately forgotten, never updated again and just rot in there.

**Comment by babycaseny** [comment]
Sorry, I think I have done things in the wrong direction. I intended to pull from your side to mine.  I will stick to command line next time.

**Pull request closed without merging**
